version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/angular-demo"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "fluid-framework"
      - dependency-name: "@fluidframework/*"

  - package-ecosystem: "npm"
    directory: "/audience-demo"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "fluid-framework"
      - dependency-name: "@fluidframework/*"

  - package-ecosystem: "npm"
    directory: "/brainstorm"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "fluid-framework"
      - dependency-name: "@fluidframework/*"

  - package-ecosystem: "collaborative-text-area"
    directory: "/angular-demo"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "fluid-framework"
      - dependency-name: "@fluidframework/*"

  - package-ecosystem: "npm"
    directory: "/multi-framework-diceroller"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "fluid-framework"
      - dependency-name: "@fluidframework/*"

  - package-ecosystem: "npm"
    directory: "/node-demo"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "fluid-framework"
      - dependency-name: "@fluidframework/*"

  - package-ecosystem: "npm"
    directory: "/react-demo"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "fluid-framework"
      - dependency-name: "@fluidframework/*"

  - package-ecosystem: "npm"
    directory: "/react-starter-template"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "fluid-framework"
      - dependency-name: "@fluidframework/*"

  - package-ecosystem: "npm"
    directory: "/teams-fluid-hello-world"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "fluid-framework"
      - dependency-name: "@fluidframework/*"
