version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    reviewers: 
      - "microsoft/fluid-cr-devx"
    # Look for `package.json` and `package-lock.json` files in these directories
    directories:
      - "/"
      - "/brainstorm"
      - "/item-counter"
      - "/item-counter-spe"
    schedule:
      interval: "daily"
    groups:
      fluid-framework-dependencies:
        patterns:
          - "@fluidframework*" 
          - "fluid-framework"
      typescript-eslint:
        patterns:
          - "@typescript-eslint"
