version: 2
updates:
  # Daily updates for Fluid Framework dependencies
  - package-ecosystem: "npm"
    reviewers:
      - "microsoft/fluid-cr-devx"
    # Look for `package.json` and `package-lock.json` files in these directories
    directories:
      - "/"
      - "/brainstorm"
      - "/item-counter"
      - "/item-counter-spe"
    schedule:
      interval: "daily"
    groups:
      fluid-framework-dependencies:
        patterns:
          - "@fluidframework*"
          - "fluid-framework"
    # This makes it possible to have another config for the same directories
    target-branch: "main"

  # Weekly updates for all other dependencies
  - package-ecosystem: "npm"
    reviewers:
      - "microsoft/fluid-cr-devx"
    directories:
      - "/"
      - "/brainstorm"
      - "/item-counter"
      - "/item-counter-spe"
    schedule:
      interval: "weekly"
    groups:
      # To reduce noise, we bundle related dependencies into a single PR
      eslint:
        patterns:
          - "*eslint*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
    ignore:
      - dependency-name: "@fluidframework*"
      - dependency-name: "fluid-framework"
