version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    reviewers: 
      - "microsoft/fluid-cr-devx"
    # Look for `package.json` and `package-lock.json` files in these directories
    directories:
      - "/"
      - "/brainstorm"
      - "/item-counter"
      - "/item-counter-spe"
    schedule:
      interval: "weekly"
    groups:
      # We want to update all Fluid dependencies simultaneously to keep them in sync.
      fluid-framework-dependencies:
        patterns:
          - "@fluidframework*" 
          - "fluid-framework"
      # To reduce noise, we bundle related dependencies into a single PR.
      eslint:
        patterns:
          - "*eslint*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
