# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# FluidExamples build for CI and PR

pool:
  vmImage: ubuntu-latest

parameters:
- name: brainstorm
  type: string
  default: brainstorm
- name: react-starter-template
  type: string
  default: react-starter-template
- name: react-demo
  type: string
  default: react-demo
- name: multi-framework-diceroller
  type: string
  default: multi-framework-diceroller
- name: node-demo
  type: string
  default: node-demo
<<<<<<< HEAD
=======
- name: teams-fluid-hello-world
  type: string
  default: teams-fluid-hello-world
>>>>>>> 46ea7f4f2eaf4d90c34aec51741c05e6d38703a5

trigger:
- main

pr:
- main

variables:
  skipComponentGovernanceDetection: true

steps:
- task: ComponentGovernanceComponentDetection@0
  inputs:
    scanType: 'Register'
    verbosity: 'Verbose'
    alertWarningLevel: 'High'

- task: UseNode@1
  displayName: Use Node 12.x
  inputs: 
    version: 12.x

- ${{ each parameter in parameters }}:
  - task: Npm@1
    displayName: Install - ${{ parameter.Value }}
    inputs:
      command: 'custom'
      workingDir: '${{ parameter.Value }}'
      customCommand: 'install'
  - task: Npm@1
    displayName: Build - ${{ parameter.Value }}
    inputs:
      command: 'custom'
      workingDir: ${{ parameter.Value }}
      customCommand: 'run build'
  - task: Npm@1
    displayName: Test - ${{ parameter.Value }}
    inputs:
      command: 'custom'
      workingDir: ${{ parameter.Value }}
      customCommand: 'run test:report'
  - task: PublishTestResults@2
    displayName: Publish Test Results - ${{ parameter.Value }}
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/*junit-report.xml'
      searchFolder: ${{ parameter.Value }}/nyc
      mergeTestResults: true
    condition: succeededOrFailed()
