# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# FluidExamples build for CI and PR

parameters:
  - name: brainstorm
    type: string
    default: brainstorm
  - name: item-counter
    type: string
    default: item-counter
  - name: item-counter-spe
    type: string
    default: item-counter-spe
schedules:
  - cron: "0 16 * * 1-5"
    displayName: Daily builds
    branches:
      include:
        - main
    always: true
trigger:
  - main
pr:
  - main
variables:
  skipComponentGovernanceDetection: true
resources:
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: Small-eastus2
      os: linux
    sdl:
      sourceAnalysisPool:
        name: Azure-Pipelines-1ESPT-ExDShared
        image: windows-2022
        os: windows
    customBuildTags:
      - ES365AIMigrationTooling
    stages:
      - stage: stage
        jobs:
          - job: job
            steps:
              - task: ComponentGovernanceComponentDetection@0
                inputs:
                  scanType: "Register"
                  verbosity: "Verbose"
                  alertWarningLevel: "High"
              - task: UseNode@1
                displayName: Use Node 20.x
                inputs:
                  version: 20.x
              - ${{ each parameter in parameters }}:
                  - task: Npm@1
                    displayName: Install - ${{ parameter.Value }}
                    inputs:
                      command: "custom"
                      workingDir: "${{ parameter.Value }}"
                      customCommand: "ci"
                  - task: CmdLine@2
                    displayName: Build - ${{ parameter.Value }}
                    inputs:
                      script: "npm run build"
                      workingDirectory: ${{ parameter.Value }}
                  - task: CmdLine@2
                    displayName: Lint - ${{ parameter.Value }}
                    inputs:
                      script: "npm run lint"
                      workingDirectory: ${{ parameter.Value }}
                  - task: CmdLine@2
                    displayName: Test - ${{ parameter.Value }}
                    inputs:
                      script: "npm run ci:test"
                      workingDirectory: ${{ parameter.Value }}
                  - task: PublishTestResults@2
                    displayName: Publish Test Results - ${{ parameter.Value }}
                    inputs:
                      testResultsFormat: "JUnit"
                      testResultsFiles: "junit-report.xml"
                      searchFolder: ${{ parameter.Value }}/test-results
                      mergeTestResults: true
                    condition: succeededOrFailed()
